name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-lastest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print Goodbye
        run: echo "Done - bye!"
